import express from 'express';
import { createPolice, scanFaces, stats, users } from '../controllers/adminController.js';
import { requireAuth, requireRole } from '../middleware/auth.js';
import { upload } from '../utils/upload.js';
const router = express.Router();
router.use(requireAuth, requireRole('admin'));
router.get('/stats', stats);
router.get('/users', users);
router.post('/police', createPolice);
router.post('/scan-face', upload.single('image'), scanFaces);
export default router;
